services:
  sdk:
    image: bboehmke/pebble-dev
    environment:
      - DISPLAY
    volumes:
      - ./docker/browser.py:/opt/pebble-sdk-4.5-linux64/pebble-tool/pebble_tool/util/browser.py
      - /tmp/.X11-unit:/tmp.X11-unit
      - ~/.Xauthority:/home/pebble/.Xauthority
      - ./app:/pebble
    network_mode: host
